### ISSUE TITLE
Upgrade to pion/webrtc@v3

### ISSUE THREAD

**Issue by Sean-Der** [termbacktime/termbacktime#22]
Hey @LouisT  Really great project. I just had a blast playing with it, such a great tool for teaching :) 

Would you be open to a PR updating to [v3](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0)? It will require one change to disable Trickle ICE. If you are up for changing the frontend to enable Trickle ICE you may see faster startup times.

More people need to know about this project also! You should make a `Show HN` post, would also love to drop a tweet on twitter.com/_pion 

thanks!

**Comment by LouisT** [comment]
Hello! I've been looking into upgrading to v3, the only issue I've discovered is that I've done the connections in reverse. At the moment the data channel is created BEFORE the websocket is connected, so to use the new method I'll have to switch the order. In the mean time, I've made the update using the `GatheringCompletePromise` call. I'll put those on the `dev` branch today (#23) or possibly `master` release under rc.5 since no major breaking changes have been added. I'm currently adding a bit of temporary file logging for things like WebRTC errors as I don't want to display those in the terminal while processes are running or something.

I've made posts about this project on [Reddit](https://www.reddit.com/r/golang/comments/gxlck5/update_termbacktime_v100beta2_live_terminal/) but it's been a while. Not really sure where else to "advertise", I'll take a look at `Show HN`. What would I have to do for a tweet?

**Comment by LouisT** [comment]
Alright @Sean-Der I've pushed the v3 update as `1.0.0-rc.5`. Will have to look into reversing the connection order later down the line.

**Comment by Sean-Der** [comment]
That's great news! Closing since it looks like everything was a success :) 

I am happy to re-tweet something you have OR I can write one myself. If you have anything in particular you want me to call out just tell me. `Show HN` is huge another Pion project just did one and was really successful https://news.ycombinator.com/item?id=25627673

The big things I have seen that mattered
* A title that sells why people would be interested (ShowHN: termbacktime record and share your terminal over the web) something like that....
* Make the first post that goes into details why you built it/goals etc...
